import type { Card } from "@/shared/types";

export const DEMO_CARDS: Card[] = [
  {
    id: "demo-1",
    word: "mitigate",
    phonetic: "/ˈmɪtɪɡeɪt/",
    meaningVi: "giảm thiểu",
    meaningEn: "to make something less severe or serious",
    example: "The new policy aims to mitigate the effects of climate change.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "demo-2",
    word: "ambiguous",
    phonetic: "/æmˈbɪɡjuəs/",
    meaningVi: "mơ hồ, không rõ ràng",
    meaningEn: "open to more than one interpretation",
    example: "Her answer was deliberately ambiguous.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "demo-3",
    word: "procrastinate",
    phonetic: "/proʊˈkræstɪneɪt/",
    meaningVi: "trì hoãn",
    meaningEn: "to delay doing something",
    example: "Stop procrastinating and finish your report.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "demo-4",
    word: "resilient",
    phonetic: "/rɪˈzɪliənt/",
    meaningVi: "kiên cường, dễ phục hồi",
    meaningEn: "able to recover quickly from difficulties",
    example: "Children are often remarkably resilient.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "demo-5",
    word: "meticulous",
    phonetic: "/məˈtɪkjələs/",
    meaningVi: "tỉ mỉ, cẩn thận",
    meaningEn: "showing great attention to detail",
    example: "She kept meticulous records of every transaction.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "demo-6",
    word: "eloquent",
    phonetic: "/ˈeləkwənt/",
    meaningVi: "hùng biện, lưu loát",
    meaningEn: "fluent and persuasive in speaking or writing",
    example: "He gave an eloquent speech at the conference.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "demo-7",
    word: "inevitable",
    phonetic: "/ɪˈnevɪtəbl/",
    meaningVi: "không thể tránh khỏi",
    meaningEn: "certain to happen; unavoidable",
    example: "Change is inevitable in any growing company.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "demo-8",
    word: "versatile",
    phonetic: "/ˈvɜːrsətl/",
    meaningVi: "đa năng, linh hoạt",
    meaningEn: "able to adapt to many different functions",
    example: "This is a versatile ingredient used in many dishes.",
    deckId: "demo",
    createdAt: "",
    updatedAt: "",
  },
];
